#!/command/with-contenv bash
# shellcheck shell=bash

echo '
───────────────────────────────────────
FulltextSearch live service
───────────────────────────────────────'

if [[ -d /var/www/apps/fulltextsearch ]]; then
    # If fulltextsearch is present: stop all running indexes before start live.
    s6-setuidgid www-data php /var/www/occ fulltextsearch:stop

    # If fulltextsearch is present: start live index
    s6-setuidgid www-data php /var/www/occ fulltextsearch:live

    echo '
Status:      enabled'
else
    echo '
Status:      disabled'
fi
echo '───────────────────────────────────────'

